version: '3.7'
services:
  jenkins:
    image: jenkins/jenkins:lts-jdk11
    container_name: jenkins
    restart: always
    privileged: true
    user: root
    environment:
      TZ: "Asia/Seoul"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./jenkins_home:/var/jenkins_home
    ports:
      - 8080:8080
      - 50000:50000
  spring:
    container_name: spring-boot
    restart: always
    build:
      context: ./
      dockerfile: dockerfile
    ports:
    - 8085:8080
    volumes:
    - ~/jenkins_home/workspace/jenkins_test_main/build/libs:/deploy